### ISSUE TITLE
Gerrit Secuce Connection Failed behind HAProxy

### ISSUE THREAD

**Issue by dzintars** [oswee/oswee#373]
This is working example:

```yaml
          env:
            - name: CANONICAL_WEB_URL
              value: https://gerrit.oswee.dev
            - name: HTTPD_LISTEN_URL
              value: proxy-https://*:8080
```

I tried `proxy-https://127.0.0.1:8080` and `proxy-https://localhost:8080` which booth fails to run in rootless container.
